name: Release

on:
  release:
    types: [ published ]
  # push:
  #   branches:
  #     - main

permissions:
  contents: read

jobs:
  deployment:
    name: Release to Cloudflare
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - run: npm install

      - run: npm run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy dist --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }} --branch=main